version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform..."
      - curl -fsSL -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.15.0/terraform_1.15.0_linux_amd64.zip
      - unzip -o /tmp/terraform.zip -d /tmp/terraform
      - install /tmp/terraform/terraform /usr/local/bin/terraform
      - terraform version

  pre_build:
    commands:
      - echo "Moving to Day 3 workload..."
      - cd day3/workload
      - echo "Initializing Terraform..."
      - terraform init -input=false
      - echo "Validating Terraform..."
      - terraform validate

  build:
    commands:
      - echo "Applying Terraform..."
      - terraform apply -input=false -auto-approve tfplan

  post_build:
    commands:
      - echo "Terraform apply completed successfully."